### ISSUE TITLE
TestMode URL

### ISSUE THREAD

**Issue by JJSchaart** [cardgate/omnipay-cardgate#1]
https://api-test.cardgate.com > https://secure-staging.curopayments.net

**Comment by J-Brk** [comment]
1,5 year later, still not resolved 👎

**Comment by cardgate** [comment]
Unfortunately it completely slipped under our radar, for which we apologise. Urls are updated.

**Comment by J-Brk** [comment]
@cardgate Thanks! Please publish the changes to tag 2.0 too

**Comment by JJSchaart** [comment]
Thanks @cardgate!
